# Generated by Django 4.1 on 2022-10-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=35)),
                ("description", models.CharField(max_length=250)),
                ("title_bottom_left", models.CharField(max_length=85)),
                ("info_bottom_right", models.CharField(max_length=250)),
            ],
        ),
    ]
