# Generated by Django 4.1 on 2022-10-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="info_bottom_left",
            field=models.CharField(default="some info", max_length=250),
            preserve_default=False,
        ),
    ]
