# Generated by Django 4.1 on 2022-10-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_profile", "0003_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("advantage1", models.CharField(max_length=250)),
                ("advantage2", models.CharField(max_length=250)),
                ("advantage3", models.CharField(max_length=250)),
            ],
        ),
    ]
