# Generated by Django 4.1 on 2022-10-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_profile", "0004_advantage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=35)),
                ("mail", models.EmailField(max_length=50)),
                ("phone", models.CharField(max_length=12)),
                ("message", models.TextField()),
            ],
        ),
    ]
