# Generated by Django 4.1 on 2022-10-21 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_profile", "0005_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="phone",
            field=models.CharField(
                default="+7",
                max_length=12,
                validators=[
                    django.core.validators.MinLengthValidator(12),
                    django.core.validators.RegexValidator(
                        message="Номер телефона может содержать только цифры",
                        regex="+[\\d]{11}",
                    ),
                ],
            ),
        ),
    ]
