# Generated by Django 4.1 on 2022-10-21 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_profile", "0006_alter_message_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="mail",
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="phone",
            field=models.CharField(
                default="+7",
                max_length=12,
                validators=[
                    django.core.validators.MinLengthValidator(12),
                    django.core.validators.RegexValidator(
                        message="Номер телефона может содержать только цифры",
                        regex="\\+[\\d]{11}",
                    ),
                ],
            ),
        ),
    ]
