# Generated by Django 4.1 on 2022-10-22 15:12

import company_profile.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_profile", "0008_alter_message_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message",
            field=models.CharField(max_length=750),
        ),
        migrations.AlterField(
            model_name="message",
            name="name",
            field=models.CharField(
                max_length=35,
                validators=[
                    django.core.validators.RegexValidator(regex="[a-zA-Zа-яА-ЯёЁ]+")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="phone",
            field=models.CharField(
                max_length=12,
                validators=[company_profile.models.Message.regex_validators],
            ),
        ),
    ]
