# Generated by Django 4.1 on 2022-10-24 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_profile", "0009_alter_message_message_alter_message_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message", name="message", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="message",
            name="name",
            field=models.CharField(
                max_length=35,
                validators=[
                    django.core.validators.RegexValidator(regex="^[a-zA-Zа-яА-ЯёЁ]+$")
                ],
            ),
        ),
    ]
