# Generated by Django 4.1 on 2022-10-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_profile", "0010_alter_message_message_alter_message_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="message", name="time", field=models.DateField(auto_now=True),
        ),
    ]
